# Generated by Django 6.0 on 2025-12-11 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buah',
            fields=[
                ('idBuah', models.AutoField(primary_key=True, serialize=False)),
                ('namaBuah', models.CharField(max_length=50)),
                ('fotoBuah', models.ImageField(upload_to='buah_images/')),
                ('hargaBuah', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stokBuah', models.IntegerField()),
                ('deskripsiBuah', models.TextField()),
                ('diskon', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True)),
                ('lamaKesegaraan', models.IntegerField()),
                ('tanggalKadaluarsa', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('idPelanggan', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('namaPelanggan', models.CharField(max_length=70)),
                ('alamat', models.TextField()),
                ('noHp', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Pemasok',
            fields=[
                ('idPemasok', models.AutoField(primary_key=True, serialize=False)),
                ('namaPemasok', models.CharField(max_length=70)),
                ('noHp', models.CharField(max_length=12)),
                ('alamat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pembelian',
            fields=[
                ('idPembelian', models.AutoField(primary_key=True, serialize=False)),
                ('totalBuah', models.IntegerField()),
                ('totalHargaPembelian', models.DecimalField(decimal_places=2, max_digits=8)),
                ('metodeBayar', models.CharField(max_length=15)),
                ('alamatPengiriman', models.TextField(blank=True, null=True)),
                ('statusPembelian', models.CharField(max_length=10)),
                ('buktiBayar', models.ImageField(blank=True, null=True, upload_to='bukti_bayar/')),
                ('tanggalPembelian', models.DateTimeField(auto_now_add=True)),
                ('idPelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pelanggan')),
            ],
        ),
        migrations.CreateModel(
            name='DetailPembelian',
            fields=[
                ('idDetailPembelian', models.AutoField(primary_key=True, serialize=False)),
                ('kuantitas', models.IntegerField()),
                ('subHarga', models.DecimalField(decimal_places=2, max_digits=8)),
                ('idBuah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.buah')),
                ('idPembelian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pembelian')),
            ],
        ),
        migrations.CreateModel(
            name='Pengadaan',
            fields=[
                ('idPengadaan', models.AutoField(primary_key=True, serialize=False)),
                ('totalHarga', models.DecimalField(decimal_places=2, max_digits=8)),
                ('idPemasok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pemasok')),
            ],
        ),
        migrations.CreateModel(
            name='DetailPengadaan',
            fields=[
                ('idDetailPengadaan', models.AutoField(primary_key=True, serialize=False)),
                ('kuantitas', models.IntegerField()),
                ('subHarga', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tanggalMasuk', models.DateField(auto_now_add=True)),
                ('idBuah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.buah')),
                ('idPengadaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pengadaan')),
            ],
        ),
    ]
