# Generated by Django 6.0 on 2025-12-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_detailpengadaan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buah',
            name='hargaBuah',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
