# Generated by Django 6.0 on 2025-12-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_buah_hargabuah'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buah',
            name='stokBuah',
        ),
        migrations.RemoveField(
            model_name='buah',
            name='tanggalKadaluarsa',
        ),
        migrations.AlterField(
            model_name='detailpengadaan',
            name='status',
            field=models.BooleanField(default='True'),
        ),
    ]
