# Generated by Django 6.0 on 2025-12-11 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_buah_stokbuah_remove_buah_tanggalkadaluarsa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailpengadaan',
            name='idBuah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_pengadaan', to='core.buah'),
        ),
    ]
