# Generated by Django 6.0 on 2025-12-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_detailpengadaan_idbuah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembelian',
            name='metodeBayar',
            field=models.CharField(choices=[('COD', 'COD'), ('Transfer Bank BRI', 'Transfer Bank BRI')], default='COD', max_length=20),
        ),
        migrations.AlterField(
            model_name='pembelian',
            name='totalHargaPembelian',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='pengadaan',
            name='totalHarga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
