# Generated by Django 6.0 on 2025-12-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_pembelian_metodebayar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembelian',
            name='statusPembelian',
            field=models.CharField(choices=[('Menunggu', 'Menunggu'), ('Diproses', 'Diproses'), ('Selesai', 'Selesai'), ('Dibatalkan', 'Dibatalkan')], default='Menunggu', max_length=10),
        ),
    ]
