# Generated by Django 6.0 on 2025-12-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_pembelian_statuspembelian'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembelian',
            name='sudah_dikurangi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='detailpembelian',
            name='subHarga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
