# Generated by Django 6.0 on 2025-12-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pembelian_sudah_dikurangi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembelian',
            name='totalBuah',
            field=models.IntegerField(default=0),
        ),
    ]
