# Generated by Django 6.0 on 2025-12-11 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_pembelian_totalbuah'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pembelian',
            old_name='sudah_dikurangi',
            new_name='stok_dikembalikan',
        ),
    ]
