# Generated by Django 6.0 on 2025-12-14 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_sudah_dikurangi_pembelian_stok_dikembalikan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buah',
            options={'verbose_name_plural': 'Buah'},
        ),
        migrations.AlterModelOptions(
            name='detailpembelian',
            options={'verbose_name_plural': 'Detail Pembelian'},
        ),
        migrations.AlterModelOptions(
            name='detailpengadaan',
            options={'verbose_name_plural': 'Detail Pengadaan'},
        ),
        migrations.AlterModelOptions(
            name='pelanggan',
            options={'verbose_name_plural': 'Pelanggan'},
        ),
        migrations.AlterModelOptions(
            name='pemasok',
            options={'verbose_name_plural': 'Pemasok'},
        ),
        migrations.AlterModelOptions(
            name='pembelian',
            options={'verbose_name_plural': 'Pembelian'},
        ),
        migrations.AlterModelOptions(
            name='pengadaan',
            options={'verbose_name_plural': 'Pengadaan'},
        ),
    ]
