# Generated by Django 6.0 on 2025-12-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_buah_options_alter_detailpembelian_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembelian',
            name='totalBuah',
            field=models.IntegerField(default='Otomatis'),
        ),
        migrations.AlterField(
            model_name='pembelian',
            name='totalHargaPembelian',
            field=models.DecimalField(decimal_places=2, default='Otomatis', max_digits=8),
        ),
        migrations.AlterField(
            model_name='pengadaan',
            name='totalHarga',
            field=models.DecimalField(decimal_places=2, default='Otomatis', max_digits=8),
        ),
    ]
