# Generated by Django 6.0 on 2025-12-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_pembelian_totalbuah_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailpembelian',
            name='subHarga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='detailpengadaan',
            name='subHarga',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='pembelian',
            name='totalHargaPembelian',
            field=models.DecimalField(decimal_places=2, default='Otomatis', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pengadaan',
            name='totalHarga',
            field=models.DecimalField(decimal_places=2, default='Otomatis', max_digits=10),
        ),
    ]
