# Generated by Django 6.0 on 2025-12-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_detailpembelian_subharga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembelian',
            name='totalBuah',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pembelian',
            name='totalHargaPembelian',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pengadaan',
            name='totalHarga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
