# Generated by Django 6.0 on 2025-12-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_pembelian_totalbuah_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembelian',
            name='tanggalPembelian',
            field=models.DateField(auto_now_add=True),
        ),
    ]
