# Generated by Django 6.0 on 2025-12-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_pembelian_tanggalpembelian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembelian',
            name='tanggalPembelian',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
