# Generated by Django 6.0 on 2026-06-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_pembelian_tanggalpembelian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buah',
            name='diskon',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='pembelian',
            name='alamatPengiriman',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pembelian',
            name='buktiBayar',
            field=models.ImageField(upload_to='bukti_bayar/'),
        ),
    ]
