# Generated by Django 5.2.15 on 2026-07-02 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_buah_diskon_alter_pembelian_alamatpengiriman_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('idKaryawan', models.AutoField(primary_key=True, serialize=False)),
                ('namaKaryawan', models.CharField(max_length=70)),
                ('noHp', models.CharField(max_length=12, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Karyawan',
            },
        ),
        migrations.CreateModel(
            name='LogAktivitasKaryawan',
            fields=[
                ('idLog', models.AutoField(primary_key=True, serialize=False)),
                ('aksi', models.CharField(choices=[('CREATE', 'CREATE'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE')], max_length=10)),
                ('target_model', models.CharField(choices=[('Buah', 'Buah'), ('Pembelian', 'Pembelian'), ('Pelanggan', 'Pelanggan')], max_length=20)),
                ('target_id', models.IntegerField()),
                ('deskripsi', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('idKaryawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.karyawan')),
            ],
            options={
                'verbose_name_plural': 'Log Aktivitas Karyawan',
            },
        ),
    ]
