# Generated by Django 5.2.15 on 2026-07-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_karyawan_logaktivitaskaryawan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilToko',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_toko', models.CharField(default='GERAI BUAH ARB', max_length=100)),
                ('alamat', models.TextField()),
                ('telepon', models.CharField(max_length=20)),
                ('footer_pesan', models.TextField()),
                ('logo_struk', models.ImageField(blank=True, null=True, upload_to='logo_struk/')),
            ],
            options={
                'verbose_name_plural': 'Profil Toko',
            },
        ),
    ]
