# Generated by Django 5.2.15 on 2026-07-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_profiltoko_qris_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembelian',
            name='jasa_kirim',
            field=models.CharField(blank=True, choices=[('', 'Tidak Ada / Belum Ditentukan'), ('Grab', 'Grab'), ('Maxim', 'Maxim'), ('GoSend', 'GoSend / Gojek'), ('Lalamove', 'Lalamove'), ('Kurir Sendiri', 'Kurir Sendiri'), ('Ambil Sendiri', 'Ambil Sendiri'), ('Lainnya', 'Lainnya')], default='', max_length=30, verbose_name='Jasa Kirim'),
        ),
        migrations.AddField(
            model_name='pembelian',
            name='nama_kurir',
            field=models.CharField(blank=True, default='', help_text='Opsional: nama pengemudi atau kontak kurir', max_length=100, verbose_name='Nama Kurir'),
        ),
        migrations.AddField(
            model_name='pembelian',
            name='ongkos_kirim',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Dibayar cash langsung ke kurir, terpisah dari harga buah', max_digits=8, verbose_name='Ongkos Kirim'),
        ),
        migrations.AlterField(
            model_name='pembelian',
            name='buktiBayar',
            field=models.ImageField(blank=True, null=True, upload_to='bukti_bayar/'),
        ),
    ]
