# Generated by Django 5.2.15 on 2026-07-23 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_jasa_kirim_ongkos_kirim_to_pembelian'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailpengadaan',
            name='grade',
            field=models.CharField(choices=[('segar', '🟢 Segar'), ('menengah', '🟡 Menengah'), ('hampir_rusak', '🟠 Hampir Rusak'), ('rusak', '🔴 Rusak')], default='segar', help_text='Kondisi buah saat masuk/saat ini', max_length=15, verbose_name='Grade / Kondisi'),
        ),
        migrations.AddField(
            model_name='detailpengadaan',
            name='kuantitas_awal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detailpengadaan',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='logaktivitaskaryawan',
            name='target_model',
            field=models.CharField(choices=[('Buah', 'Buah'), ('Pembelian', 'Pembelian'), ('Pelanggan', 'Pelanggan'), ('CatatanKerusakan', 'Catatan Kerusakan'), ('ProdukOlahan', 'Produk Olahan'), ('DetailPengadaan', 'Detail Pengadaan')], max_length=20),
        ),
        migrations.CreateModel(
            name='CatatanKerusakan',
            fields=[
                ('idKerusakan', models.AutoField(primary_key=True, serialize=False)),
                ('qty_rusak', models.IntegerField(verbose_name='Jumlah Rusak (kg)')),
                ('kuantitas_sebelum', models.IntegerField(default=0, help_text='Snapshot kuantitas batch sebelum kerusakan dicatat (otomatis)', verbose_name='Stok Sebelum Dicatat')),
                ('alasan', models.CharField(choices=[('busuk_kadaluarsa', 'Busuk / Kadaluarsa'), ('rusak_fisik', 'Rusak Fisik / Jatuh'), ('hama', 'Hama / Ulat'), ('lainnya', 'Lainnya')], max_length=20, verbose_name='Alasan Kerusakan')),
                ('keterangan', models.TextField(blank=True, default='', verbose_name='Keterangan Tambahan')),
                ('nilai_kerugian', models.DecimalField(decimal_places=2, default=0, help_text='Dihitung otomatis: qty_rusak × harga_beli_per_kg', max_digits=10, verbose_name='Nilai Kerugian (ribu Rp)')),
                ('tanggalDicatat', models.DateTimeField(auto_now_add=True)),
                ('idDetailPengadaan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catatan_kerusakan', to='core.detailpengadaan', verbose_name='Batch Pengadaan')),
                ('idKaryawan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.karyawan', verbose_name='Dicatat Oleh')),
            ],
            options={
                'verbose_name': 'Catatan Kerusakan',
                'verbose_name_plural': 'Catatan Kerusakan',
                'ordering': ['-tanggalDicatat'],
            },
        ),
        migrations.CreateModel(
            name='ProdukOlahan',
            fields=[
                ('idProdukOlahan', models.AutoField(primary_key=True, serialize=False)),
                ('nama_produk', models.CharField(help_text='Contoh: Jus Mangga, Salad Buah', max_length=100, verbose_name='Nama Produk Olahan')),
                ('qty_bahan_dipakai', models.IntegerField(verbose_name='Bahan Dipakai (kg)')),
                ('qty_produk_jadi', models.IntegerField(verbose_name='Produk Jadi (unit/gelas/bungkus)')),
                ('harga_jual_per_unit', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Harga Jual per Unit (ribu Rp)')),
                ('total_pendapatan', models.DecimalField(decimal_places=2, default=0, help_text='Dihitung otomatis: qty_produk_jadi × harga_jual_per_unit', max_digits=10, verbose_name='Total Pendapatan (ribu Rp)')),
                ('tanggal', models.DateField(verbose_name='Tanggal Olah')),
                ('catatan', models.TextField(blank=True, default='', verbose_name='Catatan')),
                ('idDetailPengadaan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produk_olahan', to='core.detailpengadaan', verbose_name='Batch Bahan (Hampir Rusak)')),
                ('idKaryawan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.karyawan', verbose_name='Dicatat Oleh')),
            ],
            options={
                'verbose_name': 'Produk Olahan',
                'verbose_name_plural': 'Produk Olahan',
                'ordering': ['-tanggal'],
            },
        ),
    ]
