# Generated by Django 5.2.15 on 2026-07-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_grade_kerusakan_produk_olahan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkolahan',
            name='idDetailPengadaan',
        ),
        migrations.RemoveField(
            model_name='produkolahan',
            name='idKaryawan',
        ),
        migrations.AlterField(
            model_name='detailpengadaan',
            name='grade',
            field=models.CharField(choices=[('segar', 'Segar'), ('menengah', 'Menengah'), ('hampir_rusak', 'Hampir Rusak'), ('rusak', 'Rusak')], default='segar', max_length=15),
        ),
        migrations.AlterField(
            model_name='detailpengadaan',
            name='kuantitas_awal',
            field=models.IntegerField(default=0, help_text='Snapshot kuantitas awal'),
        ),
        migrations.AlterField(
            model_name='detailpengadaan',
            name='status',
            field=models.BooleanField(default='True'),
        ),
        migrations.AlterField(
            model_name='logaktivitaskaryawan',
            name='target_model',
            field=models.CharField(choices=[('Buah', 'Buah'), ('Pembelian', 'Pembelian'), ('Pelanggan', 'Pelanggan')], max_length=20),
        ),
        migrations.DeleteModel(
            name='CatatanKerusakan',
        ),
        migrations.DeleteModel(
            name='ProdukOlahan',
        ),
    ]
