# Generated by Django 5.2.15 on 2026-07-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_logaktivitaskaryawan_target_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailpengadaan',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
