# Generated by Django 5.2.15 on 2026-07-24 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_buah_diskon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailpengadaan',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='detailpengadaan',
            name='kuantitas',
        ),
        migrations.AddField(
            model_name='detailpengadaan',
            name='qty_hampir_rusak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detailpengadaan',
            name='qty_menengah',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detailpengadaan',
            name='qty_rusak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detailpengadaan',
            name='qty_segar',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detailpengadaan',
            name='kuantitas_awal',
            field=models.IntegerField(default=0, help_text='Snapshot kuantitas awal (total kotor)'),
        ),
        migrations.AlterField(
            model_name='detailpengadaan',
            name='subHarga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
