# Generated by Django 5.2.15 on 2026-07-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_detailpengadaan_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailpengadaan',
            name='kuantitas_awal',
        ),
        migrations.AddField(
            model_name='detailpengadaan',
            name='kuantitas',
            field=models.IntegerField(default=0, help_text='Kuantitas total kotor nota'),
        ),
        migrations.AlterField(
            model_name='produkolahan',
            name='tanggal',
            field=models.DateField(auto_now_add=True, verbose_name='Tanggal Olah'),
        ),
    ]
