# Generated by Django 5.2.15 on 2026-07-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_detailpengadaan_kuantitas_awal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengadaan',
            name='totalHarga',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
