# Generated by Django 5.2.15 on 2026-07-24 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_pengadaan_totalharga'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenjualanOlahan',
            fields=[
                ('idPenjualanOlahan', models.AutoField(primary_key=True, serialize=False)),
                ('nama_pelanggan', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nama Pelanggan')),
                ('qty', models.IntegerField(verbose_name='Kuantitas (Unit)')),
                ('tanggal', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Penjualan')),
                ('pencatat', models.CharField(max_length=150, verbose_name='Dicatat Oleh')),
                ('bukti_pembelian', models.ImageField(blank=True, null=True, upload_to='bukti_olahan/', verbose_name='Bukti Pembayaran')),
                ('idProdukOlahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produkolahan', verbose_name='Produk Olahan')),
            ],
            options={
                'verbose_name': 'Penjualan Olahan',
                'verbose_name_plural': 'Penjualan Olahan',
            },
        ),
    ]
