"""
Django settings for randiTA project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-s##p^gb@z=trpmhv5j%5oybhwb_mv*ui#u57ap(lsq8#yoqnot'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    'GeraiBuahARB.pythonanywhere.com',
    'localhost',
    '127.0.0.1',
]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'randiTA.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.kesegaran_alert',  # Freshness Alert System
            ],
        },
    },
]

WSGI_APPLICATION = 'randiTA.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'id'

TIME_ZONE = 'Asia/Makassar'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
import os
# STATIC_URL = 'static/'
# STATIC_URL = '/static/'
# STATICFILES_DIRS = [
#     BASE_DIR / 'static', # Pastikan ini menunjuk ke folder static di level project
# ]

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

JAZZMIN_SETTINGS = {
    "site_title": "Admin Gerai Buah ARB",
    "site_header": "Admin Gerai Buah ARB",
    "site_brand": "Gerai Buah ARB",
    "welcome_sign": "Gerai Buah ARB Admin",
    "goodbye_sign": "Terima Kasih Telah Berkunjung, Sampai Jumpa Kembali",

    "site_logo": "img/fruits.png",
    
    # Custom menu links for reporting system
    "custom_links": {
        "core": [
            {
                "name": "Laporan",
                "url": "/admin/laporan/",
                "icon": "fas fa-chart-bar",
                "permissions": ["core.view_buah"]
            },
        ]
    },
    
     "order_with_respect_to": [
        "core.Buah",         # Posisi 1
        "core.Pelanggan",     # Posisi 2
        "core.Pembelian",     # Posisi 3
        "core.DetailPembelian",     # Posisi 4
        "core.Pemasok",   # Posisi 5
        "core.Pengadaan",     # Posisi 6
        "core.DetailPengadaan",     # Posisi 7
    ],

     "icons": {
        # "auth": "fas fa-users-cog",
        # "auth.user": "fas fa-user",
        # "auth.Group": "fas fa-users",
        "Core.Mahasiswa": "fas fa-user-graduate",
        "Core.Dosen": "fas fa-chalkboard-teacher",
        "Core.JadwalUjian": "fas fa-calendar-alt",
        "core.Buah": "fa-solid fa-apple-whole",    # Posisi 1
        "core.Pelanggan": "fa-solid fa-user-group",     # Posisi 2
        "core.Pembelian": "fa-solid fa-cart-shopping",     # Posisi 3
        "core.DetailPembelian": "fa-solid fa-cart-shopping",     # Posisi 4
        "core.Pemasok": "fa-solid fa-address-book",   # Posisi 5
        "core.Pengadaan": "fa-solid fa-truck",     # Posisi 6
        "core.DetailPengadaan": "fa-solid fa-truck",     # Posisi 7
    },
    "show_ui_builder":"True",
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-success navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-success",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}